#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:          touch-waypoint.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Camera touch-waypoints
# Description: Manage the touchscreen waypoint service
### END INIT INFO

case "$1" in
  start)
    echo "Starting touch-waypoint.py"
    exec start-stop-daemon --start -c pi --exec /usr/local/bin/touch-waypoint.py
    ;;
  stop)
    echo "Stopping touch-waypoint.py"
    pkill -f /usr/local/bin/touch-waypoint.py
    ;;
  *)
    echo "Usage: /etc/init.d/touch-waypoint.sh {start|stop}"
    exit 1
    ;;
esac

exit 0
